### ISSUE TITLE
Pin mapping table is cut off

### ISSUE THREAD

**Issue by scuda** [macchina/docs#11]
The [license](http://docs.macchina.cc/) needs to same width as the other content. It also appears at the bottom of [pages](http://docs.macchina.cc/m2/overview/). 

The left most column of [pin mapping table](http://docs.macchina.cc/m2/processor/pin-mapping.html) is cut off.

**Comment by adamvoss** [comment]
> It also appears at the bottom of pages.

That bit was by design.  Did you have a different approach in mind?

**Comment by scuda** [comment]
No that is fine we just need to resize it in both places.

**Comment by adamvoss** [comment]
Fixed by #29
