### ISSUE TITLE
Do we really want all links orange?

### ISSUE THREAD

**Issue by adamvoss** [macchina/docs#14]
The orange links really stood out to me on first run.  The main macchina website uses the conventional blue and having them all orange seemed loud to me, but perhaps it is just first impression.

![image](https://user-images.githubusercontent.com/965439/29421152-c31ad4c0-8339-11e7-817a-7c9cb55c0d21.png)

Should we instead use traditional link colors within the book content?

/cc @ndiesslin

**Comment by ndiesslin** [comment]
@adamvoss I noticed that the blue color we are using for links doesn't stand out as well since the blue and black are similar in contrast. Maybe a good alternative to the orange would be using the blue color we had, but underlined by default.

**Comment by adamvoss** [comment]
That makes me wonder what is different that blue links work many places, but not here?  Do we need to main text to be grey like on the main website?

I think that, at least initially, there is probably no need to reinvent the wheel; the browser standard colors work many many places, or the colors used somewhere like Wikipedia, which has a lot of readers, could be inspected to see what works.  I don't think links need the attention that would be given to them by making them underlined.

**Comment by adamvoss** [comment]
Fixed by #16
