### ISSUE TITLE
Add easier or clear navigation from the book to the repository

### ISSUE THREAD

**Issue by adamvoss** [macchina/docs#3]
It would be nice if it were easy for users to go from reading a page in the book to being able to actually edit that page.  

Perhaps something like the "Edit this page on GitHub" link in on the [gPodder documentation](https://gpodder.github.io/docs/), though, perhaps with a note about a free account being required.

**Comment by ndiesslin** [comment]
@adamvoss what do you think about this plugin? https://github.com/rtCamp/gitbook-plugin-edit-link The only concern I have is that it hasn't been updated in awhile.

**Comment by adamvoss** [comment]
I don't like that when you hover over the link you cannot see the destination, but it is easy and seems to work.  Integrating in in #26.  Thanks!  Sorry it took so long for me to get to this.
