### ISSUE TITLE
Pin mapping page should mention LEDs are on with LOW output

### ISSUE THREAD

**Issue by John-Titor** [macchina/docs#40]
Unlike the 'generic' Arduino LED, the M2 LEDs are on when the output is low. 

If a new user's first exposure to the LEDs is via the LED_BUILTIN define and the Blink example, they're going to be confused when the LEDs don't come on when they set the pin HIGH (since the example says HIGH is on...)

**Comment by rocketjosh** [comment]
Great suggestion, just added that note to the table. 

https://github.com/macchina/docs/commit/38dd233a7c15504c7e9cbb40cbb432672ce6545d
