### ISSUE TITLE
Add SuperB settings to boards.txt

### ISSUE THREAD

**Issue by rambohenke** [macchina/docs#49]
In the "flash SuperB with M2" guide, instead of altering the esp32 dev settings.
Have the user add the SuperB settings as an option in the boards menu.
One other big plus for me atleast is that I don't have to scroll a bunch in the list when switching between tha M2 and the SuperB.

This is my modified boards.txt from the esp32/.../.../... folder.

[boards.txt](https://github.com/macchina/docs/files/3251992/boards.txt)

**Comment by kenny-macchina** [comment]
Just tried this out and it works! I'll update the docs to reflect this easier process, thanks.
