### ISSUE TITLE
Stuck in docs...looking for link to main site

### ISSUE THREAD

**Issue by VoltVisionFrenchy** [macchina/docs#56]
Hello,
Sure you can make fun of me for this, but it has happened to me at least 5 times in the last month.  I am in the "docs" portion of the website.  I am looking for a link to the main website which includes the store and I cannot find the link.  No matter what I click on it wont take me to the main site.  I am suggesting that there should be links to get you out of "docs" and back to the main site.

respect, 
VoltVisionFrenchy (aka Steve French).

**Comment by rocketjosh** [comment]
Done!
